### ISSUE TITLE
Website bug

### ISSUE THREAD

**Issue by 1-byte-man** [Plume-org/joinplu.me#29]
Hello, when I try to open teh website it only loads the plain html text

Here is a screenshot with the bug

![imagen](https://user-images.githubusercontent.com/56204784/74038194-29987200-4996-11ea-846f-87dfe3f71c50.png)

**Comment by 1-byte-man** [comment]
> 
> 
> I can't reproduce… Do you have anything specific in your setup? Which Windows and Firefox versions? Can you reproduce with another browser and/or OS, or from another computer?

Wrong repo. It's a bug of the plume and plume docs webpage. Let me make the issue in the webpage repo

**Comment by 1-byte-man** [comment]
> 
> 
> I can't reproduce… Do you have anything specific in your setup? Which Windows and Firefox versions? Can you reproduce with another browser and/or OS, or from another computer?

I use firefox 72.0.2 in windows 7

**Comment by 1-byte-man** [comment]
Also happens in chrome 80.0.3987.87 same OS
![imagen](https://user-images.githubusercontent.com/56204784/74103492-b5d7a000-4b22-11ea-9853-0f269e53c362.png)

**Comment by 1-byte-man** [comment]
And firefox 71.0 in fedora 30
![imagen](https://user-images.githubusercontent.com/56204784/74103533-1ff04500-4b23-11ea-83e2-fbfe6ed25eb2.png)

**Comment by elegaanz** [comment]
Are you always on the same network connection? Could you try from another place? I still can't reproduce…

**Comment by 1-byte-man** [comment]
Ok. I'll try later. I'm gonna send you the results

**Comment by krkk** [comment]
I think that server tries to match the language code to the file extension.

In most cases (e.g. `Accept-Language: fr` or `de`) it will return `text/html` (as it should), but when it matches the file extension, it will change the Content-Type to match (e.g. `pl` → `text/x-perl`, `es` → `application/ecmascript`).

```shell
$ curl -Is https://joinplu.me | grep content-type
content-type: text/html; charset=utf-8
$ curl -IsH 'Accept-Language: pl' https://joinplu.me | grep content-type
content-type: text/x-perl; charset=utf-8
$ curl -IsH 'Accept-Language: es' https://joinplu.me | grep content-type
content-type: application/ecmascript
```

This applies only to html file(s). Images, scripts, stylesheets, and fonts work correctly.

**Comment by elegaanz** [comment]
OK, this is very weird, I'll see what's wrong with the config…

**Comment by 1-byte-man** [comment]
> 
> 
> I think that server tries to match the language code to the file extension.
> 
> In most cases (e.g. `Accept-Language: fr` or `de`) it will return `text/html` (as it should), but when it matches the file extension, it will change the Content-Type to match (e.g. `pl` → `text/x-perl`, `es` → `application/ecmascript`).
> 
> ```shell
> $ curl -Is https://joinplu.me | grep content-type
> content-type: text/html; charset=utf-8
> $ curl -IsH 'Accept-Language: pl' https://joinplu.me | grep content-type
> content-type: text/x-perl; charset=utf-8
> $ curl -IsH 'Accept-Language: es' https://joinplu.me | grep content-type
> content-type: application/ecmascript
> ```
> 
> This applies only to html file(s). Images, scripts, stylesheets, and fonts work correctly.

Yes, I've checked the http response and that's right. The browser gets the content as JavaScript instead of html. here's a screenshot
![imagen](https://user-images.githubusercontent.com/56204784/74474112-32e47b80-4e7b-11ea-8f16-d06d8d61b06f.png)

**Comment by martinszy** [comment]
This is still happening, please fix.

**Comment by KitaitiMakoto** [comment]
Hi, all.

I fixed this problem. Can you confirm? https://joinplu.me/

**Comment by KitaitiMakoto** [comment]
Sorry, I introduced another bug during fixing this `content-type` bug. So I reverted server config and this bug remains...

**Comment by KitaitiMakoto** [comment]
Again, I fixed the problem.

**Comment by martinszy** [comment]
Seems to be working fine now

**Comment by KitaitiMakoto** [comment]
@martinszy Thanks for confirmation!

I will close this issue. Feel free to reopen this and mention me when you find the same problem remains.
