### ISSUE TITLE
Issues on the list of suggested instances on the main page (TW: Suicide)

### ISSUE THREAD

**Issue by narFnarF** [Plume-org/joinplu.me#34]
I'm new to Plume and was looking for an instance to try it. I noted some issues regarding the list of instances proposed on https://joinplu.me/

1) https://plume.mastodon.host/ seems down.

2) Stemy Plume (https://plume.stemy.me/) might be abandoned and, well... the owner's last post is a suicide note. Obviously, I don't know for sure if it's real or just "poetry" but I feel this might not be appropriate to link to? Link to the specific note: https://plume.stemy.me/~/Essais/sans-issue-de-secours
(On a related note: Is there a way to contact the owner of a Plume instance? To know if they're ok?)

Sorry for this grim issue... :/

**Comment by trinity-1686a** [comment]
I've mirrored the issue on [Plume Gitea](https://git.joinplu.me/plume/joinplu.me/issues/33)

I'm not sure about deleting Stemy from the list, the instance works, and this would come akin to censorship, which I'm pretty sure will not help whoever wrote this post.

There is no way to contact the owner of an instance, however there is a contact form on the upper domain https://stemy.me/accueil/contact

**Comment by narFnarF** [comment]
I contacted the owner on Mastodon and they confirmed me that their text was a work of fiction. They added a note on the text to clarify it's not a real suicide note. 

I guess we can close this ticket now.
