### ISSUE TITLE
is project in maintenance mode

### ISSUE THREAD

**Issue by lakhininenina** [Plume-org/joinplu.me#43]
@KitaitiMakoto @elegaanz 
website says Project status: Plume is not actively maintained.

however, there is no indication of status on github. please clarify.

**Comment by KitaitiMakoto** [comment]
Do you mean writing status in README of [Plume repo](https://git.joinplu.me/Plume/Plume)?

**Comment by lakhininenina** [comment]
@KitaitiMakoto no, on [joinplu.me](https://github.com/Plume-org/joinplu.me)

**Comment by KitaitiMakoto** [comment]
Okay, I will do when I have time.

I'm interested in the background of this issue. Why isn't website enough?

**Comment by lakhininenina** [comment]
@KitaitiMakoto the website looks promising, no issues. just curious.
